import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script'; // <-- 1. IMPORTER

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        {/* 2. AJOUTER LE SCRIPT KKIAPAY ICI */}
        {/* 'beforeInteractive' garantit que le script est prêt avant que la page devienne interactive */}
        <Script
          src="https://cdn.kkiapay.me/k.js"
          strategy="beforeInteractive"
          id="kkiapay-script-layout"
        />
      </body>
    </html>
  );
}